version : "3"
networks:
  expense: #docker create network expense
volumes:
   mysql: #docker create volume mysql

services:
   mysql:
    image: sunil0428/mysql:v1
    container_name: mysql    #--name mysql
    volumes:
    - mysql:/var/lib/mysql   #-v mysql:/var/lib/mysql

   backend:
    image: sunil0428/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
    - mysql
  
   frontend:
    image: sunil0428/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend


 